### ISSUE TITLE
Adding STL export capability

### ISSUE THREAD

**Issue by MrCsabaToth** [QuentinPhilipp/strava-3D-stats#1]
I reverse engineered GitHub's Skyline (example https://skyline.github.com/QuentinPhilipp/2021) and it turns out that they use babylon JS and it has an STL export capability out of the box, that's what they use: https://doc.babylonjs.com/typedoc/classes/babylon.stlexport

**Comment by MrCsabaToth** [comment]
(They also have a pre-created gltf object and they load that with babylon, although it looks like only a gradient patch. Plus they also have a DDS file. But they also dynamically generate some stuff)

**Comment by MrCsabaToth** [comment]
You use Three JS which is alternative to babylon. Looks like Three has also STL export, one I found with quick search https://github.com/eligrey/FileSaver.js/

**Comment by MrCsabaToth** [comment]
https://www.npmjs.com/package/file-saver

**Comment by QuentinPhilipp** [comment]
Hi! Thanks for all the information you provided. I've looked into the STL export for ThreeJS and found a way to easily export the whole scene. 

It should work now, I've added a button in the UI to generate the 3D file. I would appreciate it if you could try it and give me feedback to see if the STL file is suitable for 3D printing. I'm a bit concerned by the shape generated because you have the "spikes" for the activities, but also the name written on the side and I don't know if that part can be printed correctly.

Let me know if there is a need for a fix in the export, I can maybe generate a simplified version of the model for 3d printing if necessary.

![image](https://user-images.githubusercontent.com/47563122/170645856-cd329362-9403-4a29-9ae5-7d61b751592f.png)

**Comment by MrCsabaToth** [comment]
Sweet! I'll take a look tomorrow. I'm relatively new to 3D printing, but I can tell that I don't just straight send the stl to the printer, but first it goes through a pre-processing phase. That phase for example tessellates the internals of the slab and other solid looking parts like the columns. That pre-processing step should also get rid of or smooth any jitter which could foil the 3D print. It also adds support lines if there's a concave part (not here).

I'm not sure how well the name comes out, I don't think it'll require support from the bottom because it doesn't stick out much, but now that you say it that could be a possible reason why the GitHub skyline's base slab is not a rectangular but has a slope?

But my feeling us (as a rookie 3D printer) that this will be printable. One thing is the size, I wonder how big is it, but that can be modified during the pre-processing as well.

**Comment by MrCsabaToth** [comment]
So we use a software called [cura](https://ultimaker.com/software/ultimaker-cura) for pre-processing. That's a "slicing" software, it prepares the 3D model for printing, I'm pretty sure it transforms everything which would be non printable to printable. Plus it hollows out the solid slabs and fills them with a trinagular mesh with a specific fill ratio (tunable, default 20% fill), this is mostly to speed up printing, spare the filament and the end result is still very disable mechanically. It also drops the model to the ground.

I had to rotate the model by 90 degrees, it was standing on it's side, but that's really easy. However I sized it to 150mm and the estimated print time was 6.5 hours. So I'll actually chop off most of the base to speed up print time, because a 100m wide model would be almost half that time, but I want a 150mm at least. Now I know that's why https://www.keepshape.co/gallery did it that way!

**Comment by MrCsabaToth** [comment]
I'll report back once I printed. But this STL download is already great.

**Comment by MrCsabaToth** [comment]
This got on the backburner because the hacker/maker space got closed down for a week due to a COVID exposure, and then I got busy. But eventually I'll print. I think the issue can be closed. If there will be some problem then I can open another ticket with the specifics.
