### ISSUE TITLE
Malformed HTML

### ISSUE THREAD

**Issue by MrCsabaToth** [QuentinPhilipp/strava-3D-stats#4]
I've found this closing div without the opening div

**Comment by MrCsabaToth** [comment]
Hmmm, the permalink didn't carry over: https://github.com/QuentinPhilipp/strava-3D-stats/blob/ef5f45b0b25d3ca22d7b8e48433fb56df26d496b/views/index.hbs#L41

**Comment by QuentinPhilipp** [comment]
I'll have a look.

**Comment by QuentinPhilipp** [comment]
I found three closing tags that were not supposed to be present. It has been fixed now.
